# Generated by Django 3.0.8 on 2020-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
